apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver
  namespace: default
data:
  VERSION: "1.0"
  DEBUG: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: httpserver
          imagePullPolicy: IfNotPresent
          image: zsnmwy/httpserver
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: httpserver
                  key: VERSION
            - name: Debug
              valueFrom:
                configMapKeyRef:
                  name: httpserver
                  key: DEBUG
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","while killall -2 httpserver; do sleep 5; done"]
